# Generated by Django 5.2.6 on 2025-09-19 14:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0003_rename_title_expense_description_and_more'),
        ('groups', '0004_remove_invite_email_group_accepted_members_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='settlement',
            name='expense',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='settlements', to='expenses.expense'),
        ),
    ]
