# Generated by Django 5.2.4 on 2025-08-05 11:03

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
        ('groups', '0002_invite'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='expense',
            unique_together={('group', 'paid_by')},
        ),
    ]
