# Generated by Django 5.2.4 on 2025-08-18 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_alter_expense_unique_together'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='title',
            new_name='description',
        ),
        migrations.AlterUniqueTogether(
            name='expense',
            unique_together=set(),
        ),
    ]
